import sharp from 'sharp'
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises'
import path from 'node:path'

const root = 'public/projects'
const manifest = {}
let before = 0, after = 0
async function walk(dir) {
  for (const item of await readdir(dir, { withFileTypes: true })) {
    const source = path.join(dir, item.name)
    if (item.isDirectory()) { if (item.name !== 'optimized') await walk(source); continue }
    if (!/\.(png|jpe?g|webp)$/i.test(item.name)) continue
    const relative = path.relative('public', source).replaceAll('\\', '/')
    const basename = relative.replace(/^projects\//, '').replace(/\.[^.]+$/, '').replaceAll('/', '-')
    const output = 'public/projects/optimized'
    await mkdir(output, { recursive: true })
    const metadata = await sharp(source).metadata()
    const width = Math.min(metadata.width, 1600)
    const large = `projects/optimized/${basename}-large.webp`
    const small = `projects/optimized/${basename}-small.webp`
    await sharp(source).resize({ width, withoutEnlargement: true }).webp({ quality: 88 }).toFile(`public/${large}`)
    await sharp(source).resize({ width: 640, withoutEnlargement: true }).webp({ quality: 85 }).toFile(`public/${small}`)
    manifest[relative] = { large, small, width, height: Math.round(metadata.height * width / metadata.width) }
    before += (await stat(source)).size
    after += (await stat(`public/${large}`)).size
  }
}
await walk(root)
await writeFile('src/data/image-manifest.ts', `// Generated by npm run images. Originals are preserved.\nexport const imageManifest = ${JSON.stringify(manifest, null, 2)} as const\n`)
console.log(`Optimized ${Object.keys(manifest).length} images: ${(before / 1e6).toFixed(2)} MB → ${(after / 1e6).toFixed(2)} MB (large variants).`)
