// Generated by npm run images. Originals are preserved.
export const imageManifest = {
  "projects/creative/abu-lokma.jpg": {
    "large": "projects/optimized/creative-abu-lokma-large.webp",
    "small": "projects/optimized/creative-abu-lokma-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/al-futtaim.jpg": {
    "large": "projects/optimized/creative-al-futtaim-large.webp",
    "small": "projects/optimized/creative-al-futtaim-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/aramco-saudi.jpg": {
    "large": "projects/optimized/creative-aramco-saudi-large.webp",
    "small": "projects/optimized/creative-aramco-saudi-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/big-mind-campaign.jpg": {
    "large": "projects/optimized/creative-big-mind-campaign-large.webp",
    "small": "projects/optimized/creative-big-mind-campaign-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/healthcare-fmcg-campaign.jpg": {
    "large": "projects/optimized/creative-healthcare-fmcg-campaign-large.webp",
    "small": "projects/optimized/creative-healthcare-fmcg-campaign-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/instagram-social-posts.png": {
    "large": "projects/optimized/creative-instagram-social-posts-large.webp",
    "small": "projects/optimized/creative-instagram-social-posts-small.webp",
    "width": 1600,
    "height": 1067
  },
  "projects/creative/kroma-era.png": {
    "large": "projects/optimized/creative-kroma-era-large.webp",
    "small": "projects/optimized/creative-kroma-era-small.webp",
    "width": 1600,
    "height": 833
  },
  "projects/creative/pain-book-cover.webp": {
    "large": "projects/optimized/creative-pain-book-cover-large.webp",
    "small": "projects/optimized/creative-pain-book-cover-small.webp",
    "width": 808,
    "height": 632
  },
  "projects/creative/showreel-2024.jpg": {
    "large": "projects/optimized/creative-showreel-2024-large.webp",
    "small": "projects/optimized/creative-showreel-2024-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/strong-independent.jpg": {
    "large": "projects/optimized/creative-strong-independent-large.webp",
    "small": "projects/optimized/creative-strong-independent-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/creative/vortex-company-profile.png": {
    "large": "projects/optimized/creative-vortex-company-profile-large.webp",
    "small": "projects/optimized/creative-vortex-company-profile-small.webp",
    "width": 1600,
    "height": 833
  },
  "projects/creative/vortex-retro-profile.webp": {
    "large": "projects/optimized/creative-vortex-retro-profile-large.webp",
    "small": "projects/optimized/creative-vortex-retro-profile-small.webp",
    "width": 808,
    "height": 632
  },
  "projects/creative/wara-alkawalis.jpg": {
    "large": "projects/optimized/creative-wara-alkawalis-large.webp",
    "small": "projects/optimized/creative-wara-alkawalis-small.webp",
    "width": 1196,
    "height": 1200
  },
  "projects/creative/wesal-identity.png": {
    "large": "projects/optimized/creative-wesal-identity-large.webp",
    "small": "projects/optimized/creative-wesal-identity-small.webp",
    "width": 1600,
    "height": 900
  },
  "projects/creative/zerotech-campaign.jpg": {
    "large": "projects/optimized/creative-zerotech-campaign-large.webp",
    "small": "projects/optimized/creative-zerotech-campaign-small.webp",
    "width": 1200,
    "height": 1200
  },
  "projects/kalema.png": {
    "large": "projects/optimized/kalema-large.webp",
    "small": "projects/optimized/kalema-small.webp",
    "width": 1440,
    "height": 900
  },
  "projects/kroma.webp": {
    "large": "projects/optimized/kroma-large.webp",
    "small": "projects/optimized/kroma-small.webp",
    "width": 808,
    "height": 632
  },
  "projects/pain.webp": {
    "large": "projects/optimized/pain-large.webp",
    "small": "projects/optimized/pain-small.webp",
    "width": 808,
    "height": 632
  },
  "projects/phonics.png": {
    "large": "projects/optimized/phonics-large.webp",
    "small": "projects/optimized/phonics-small.webp",
    "width": 1349,
    "height": 635
  },
  "projects/segybc.png": {
    "large": "projects/optimized/segybc-large.webp",
    "small": "projects/optimized/segybc-small.webp",
    "width": 1440,
    "height": 1050
  },
  "projects/wesal.png": {
    "large": "projects/optimized/wesal-large.webp",
    "small": "projects/optimized/wesal-small.webp",
    "width": 1440,
    "height": 900
  },
  "projects/zaman.png": {
    "large": "projects/optimized/zaman-large.webp",
    "small": "projects/optimized/zaman-small.webp",
    "width": 1440,
    "height": 1050
  }
} as const
